#!/bin/sh
# A super simple (quick) fetch shell script
# Written by Max Correia
# Dependencies: figlet

# It is just one line, but is made in the hopes of encouraging others to play around with shell scripting by showing how simple it is to string commands together
echo $(whoami)@$(hostname) $(uname -ro) | figlet
