#!/bin/sh
# A super simple (quick) fetch shell script
# Written by Max Correia
# Dependencies: figlet

# Arguments can be made for figlet fonts
if [ $1 ]
then
        echo $(whoami)@$(hostname) $(uname -sr) | figlet -f $1
else
        echo $(whoami)@$(hostname) $(uname -sr) | figlet
fi
