#!/bin/sh
# A quick script to make accessing twitch streams easier
# Written by Max Correia
# Dependencies: mpv

# Use the argument as the streamer input
# ./twitch-mpv pokemon
if [ $1 ]
then
        mpv "https://twitch.tv/"$1

# Otherwise ask for a name
else
        echo Enter the streamer you wish to view
        read streamer
        mpv --loop-file=inf "https://twitch.tv/"$streamer
fi

